<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>Latest</LangVersion>
        <Version>3.1.0</Version>
        <Nullable>enable</Nullable>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <OutputPath>..\..\RimSearcher_DataMod/Assemblies</OutputPath>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" />
      <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    </ItemGroup>

</Project>
