<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>Latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Version>3.1.2</Version>
        <AssemblyName>rimsearcher</AssemblyName>
        <Nullable>enable</Nullable>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>false</SelfContained>
        <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.*" />
        <PackageReference Include="ConsoleAppFramework" Version="5.*" />
        <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.*" />
    </ItemGroup>

</Project>
